name: ct312h_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  pocketbase: ^0.22.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  file_picker: ^9.2.1
  dio: ^5.3.2
  flutter_pdfview: ^1.4.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#ffffff" # Màu nền
  image: assets/images/app_icon.png # Đường dẫn đến logo
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/book_background.webp
    - .env
